In [1]:
!pip install -U -q autogenstudio --break-system-packages


## AutoGen Studio Installation

This cell installs the AutoGen Studio package, which is a comprehensive framework designed for building multi-agent conversational systems. AutoGen Studio provides developers with the tools needed to create sophisticated AI agents that can work together, share tasks, and handle complex workflows.

The installation uses the pip package manager with specific flags. The `--break-system-packages` flag allows installation in system Python environments, though using virtual environments is recommended for production applications. This package includes both high-level APIs for quick development and low-level components for building custom agent architectures.

Key features of AutoGen Studio include:
- Multi-agent system support for collaborative AI workflows
- Conversational AI capabilities for natural language interactions
- Both high-level and low-level APIs for different development needs
- Production-ready components for scalable deployments
- Complete framework with all necessary dependencies included

The installation process downloads and installs all required dependencies, making the system ready for immediate use in developing multi-agent applications.

In [2]:
from dotenv import load_dotenv
load_dotenv(override=True)

True

## Environment Configuration

This cell loads environment variables from a .env file to securely manage API keys and other sensitive configuration data. The `load_dotenv()` function is a standard way to handle environment variables in Python applications, ensuring that sensitive information like API keys are kept separate from the source code.

The function `load_dotenv(override=True)` performs several important tasks:
- Reads variables from a .env file in the project directory
- Makes these variables available to the application through `os.environ`
- The `override=True` parameter ensures that values in the .env file take precedence over existing environment variables
- Returns `True` when the .env file is successfully loaded

This approach follows security best practices by:
- Keeping sensitive credentials separate from source code
- Preventing accidental exposure of API keys in version control systems
- Allowing different configurations for development, testing, and production environments
- Providing a standardized way to manage application configuration

The .env file typically contains entries like `OPENAI_API_KEY=your_api_key_here`, which can then be accessed in the code using `os.environ.get('OPENAI_API_KEY')`. This pattern is widely used in professional software development for secure credential management.

In [3]:
from autogen_ext.models.openai import OpenAIChatCompletionClient
model_client = OpenAIChatCompletionClient(model="gpt-4o-mini")

## Model Client Initialization

This cell creates an OpenAI chat completion client that is configured to use the GPT-4 mini model for agent interactions. The client serves as a bridge between AutoGen agents and OpenAI's language models, handling all API communication and response processing automatically.

The `OpenAIChatCompletionClient` is initialized with the following characteristics:
- Uses the "gpt-4o-mini" model, which provides a good balance of performance and cost-effectiveness
- Automatically manages authentication using API keys from environment variables
- Handles all the technical details of communicating with OpenAI's servers
- Provides a consistent interface for AutoGen agents to interact with the language model

GPT-4 mini was chosen for this example because:
- It offers excellent performance for conversational agents and tool usage scenarios
- It has a lower cost compared to the full GPT-4 model while maintaining high quality
- It supports function calling, which is essential for tool-enhanced agents
- It has a large context window for handling longer conversations

The client automatically reads the API key from environment variables (typically `OPENAI_API_KEY`) that were loaded in the previous cell. This design ensures secure authentication without hardcoding sensitive information in the source code.

Once created, this client can be used by multiple agents throughout the application, providing a centralized way to manage model interactions and configuration.

In [4]:
from autogen_agentchat.messages import TextMessage
message = TextMessage(content="I'd like to go to London", source="user")
message

TextMessage(source='user', models_usage=None, metadata={}, content="I'd like to go to London", type='TextMessage')

## Creating a Text Message

This cell demonstrates how to create a TextMessage object, which is a fundamental data structure in AutoGen that represents user input in conversations between humans and AI agents. The TextMessage class encapsulates all the information needed for proper message handling and routing within the AutoGen system.

The TextMessage object contains several important components:
- **Content**: The actual text of the message ("I'd like to go to London" in this example)
- **Source**: Identifies who sent the message (in this case "user")
- **Type**: Automatically set to "TextMessage" for proper routing
- **Metadata**: Additional information that can be used for tracking and processing

The source parameter is particularly important because it tells the system who originated the message. Common source values include:
- "user" for messages from human users
- "assistant" or agent names for messages from AI agents
- "system" for internal system messages

This standardized message format ensures compatibility across different types of AutoGen agents and facilitates complex multi-agent interactions. The consistent structure allows agents to:
- Properly route messages to the intended recipients
- Maintain conversation history and context
- Handle different types of content appropriately
- Support features like conversation branching and message filtering

When you run this cell, it creates the TextMessage object and displays its complete structure, showing all the fields and their values. This helps you understand exactly what information is being passed between agents in the system.

In [5]:
from autogen_agentchat.agents import AssistantAgent

agent = AssistantAgent(
    name="airline_agent",
    model_client=model_client,
    system_message="You are a helpful assistant for an airline. You give short, humorous answers.",
    model_client_stream=True
)

## Basic Assistant Agent

This cell creates a simple assistant agent with custom personality traits and streaming capabilities. The AssistantAgent is one of the most commonly used agent types in AutoGen, designed to handle conversational interactions with users while maintaining specific behavioral characteristics defined by the system message.

The agent is configured with several key parameters:
- **Name**: "airline_agent" - This identifier helps distinguish this agent from others in multi-agent scenarios
- **Model Client**: Uses the OpenAI client created in the previous cell for language model access
- **System Message**: Defines the agent's personality as a helpful airline assistant that gives short, humorous answers
- **Streaming**: Enabled with `model_client_stream=True` for real-time response generation

The system message is crucial because it shapes how the agent behaves and responds. In this case, the agent is instructed to:
- Act as a helpful assistant specifically for an airline company
- Provide short responses rather than lengthy explanations
- Include humor in its responses to make interactions more engaging
- Focus on airline-related topics and customer service scenarios

Streaming is enabled to improve user experience by allowing responses to be generated and displayed in real-time rather than waiting for the complete response. This is particularly useful for longer responses or when using the agent in interactive applications.

The agent combines three essential components: a language model (through the model client), specific instructions (through the system message), and configuration settings (like streaming). This pattern demonstrates the fundamental AutoGen approach of creating specialized agents by combining these elements in different ways.

Once created, this agent can process messages, generate responses, and maintain conversations while staying true to its defined personality and role as an airline customer service assistant.

In [6]:
from autogen_core import CancellationToken

response = await agent.on_messages([message], cancellation_token=CancellationToken())
response.chat_message.content

'Sure! London: where the rain is as reliable as the Tube delays! When do you want to fly?'

## Agent Message Processing

This cell demonstrates how to send a message to an agent and receive a response using AutoGen's asynchronous message processing system. The `on_messages` method is the primary way to interact with agents, allowing you to send one or more messages and get the agent's response.

The code performs several important operations:
- **Message Processing**: The agent receives the TextMessage created in the previous cell
- **Asynchronous Execution**: Uses `await` to handle the agent's response without blocking the program
- **Cancellation Token**: Provides a mechanism to interrupt long-running operations if needed
- **Response Extraction**: Retrieves the actual response content from the agent's reply

The `CancellationToken()` is a safety feature that allows you to cancel the operation if it takes too long or if you need to stop it for any reason. This is particularly useful in production applications where you want to prevent operations from running indefinitely.

When the agent processes the message, it:
1. Receives the user's message about wanting to go to London
2. Applies its system message instructions (being helpful and humorous about airline topics)
3. Generates an appropriate response using the GPT-4 mini model
4. Returns the response in a structured format

The response object contains multiple pieces of information:
- **chat_message.content**: The actual text response from the agent
- **models_usage**: Information about token usage and API costs (if available)
- **metadata**: Additional processing information

The final line `response.chat_message.content` extracts just the text content of the agent's response, which is typically what you want to display to users or use in your application. This pattern of sending messages and extracting responses is fundamental to building conversational applications with AutoGen.

In [7]:
import os
import sqlite3

# Delete existing database file if it exists
if os.path.exists("tickets.db"):
    os.remove("tickets.db")

# Create the database and the table
conn = sqlite3.connect("tickets.db")
c = conn.cursor()
c.execute("CREATE TABLE cities (city_name TEXT PRIMARY KEY, round_trip_price REAL)")
conn.commit()
conn.close()

## Database Initialization

This cell sets up a SQLite database to store flight pricing information for different destinations. SQLite is a lightweight, file-based database that is perfect for demonstrations and development environments because it doesn't require a separate database server to be running.

The code performs several database operations:
- **File Management**: First checks if a database file named "tickets.db" already exists and removes it to start fresh
- **Database Creation**: Creates a new SQLite database connection to a file called "tickets.db"
- **Table Structure**: Creates a table named "cities" with two columns: city_name (text) and round_trip_price (real number)
- **Primary Key**: Sets city_name as the primary key, ensuring each city appears only once in the database

The database schema is designed to be simple yet functional:
- `city_name TEXT PRIMARY KEY`: Stores the name of the destination city and serves as the unique identifier
- `round_trip_price REAL`: Stores the price of a round-trip ticket to that destination as a decimal number

This database will serve as a data source for the tool-enhanced agents that we'll create later in this notebook. By having real data stored in a database, we can demonstrate how AutoGen agents can interact with external data sources to provide accurate, up-to-date information to users.

The `conn.commit()` ensures that the table creation is permanently saved to the database file, and `conn.close()` properly closes the database connection to free up resources. This pattern of connecting, performing operations, committing changes, and closing the connection is a best practice for database operations.

In [8]:
# Populate our database
def save_city_price(city_name, round_trip_price):
    conn = sqlite3.connect("tickets.db")
    c = conn.cursor()
    c.execute("REPLACE INTO cities (city_name, round_trip_price) VALUES (?, ?)", (city_name.lower(), round_trip_price))
    conn.commit()
    conn.close()

# Some cities!
save_city_price("London", 299)
save_city_price("Paris", 399)
save_city_price("Rome", 499)
save_city_price("Madrid", 550)
save_city_price("Barcelona", 580)
save_city_price("Berlin", 525)

## Database Population

This cell defines a function to insert city prices into the database and then populates it with sample roundtrip ticket prices for several popular European destinations. The function provides a reusable way to add or update pricing information in the database.

The `save_city_price` function includes several important features:
- **Parameters**: Takes two inputs - the city name as a string and the roundtrip price as a number
- **Database Connection**: Opens a connection to the same "tickets.db" file created previously
- **REPLACE Operation**: Uses `REPLACE INTO` SQL command, which either inserts a new record or updates an existing one
- **Case Normalization**: Converts city names to lowercase using `city_name.lower()` to ensure consistent data storage and searching
- **Safe Closure**: Always commits changes and closes the database connection properly

The sample data includes six major European destinations with realistic pricing:
- London: $299 - Popular destination with competitive pricing
- Paris: $399 - Slightly higher due to its status as a major tourist hub
- Rome: $499 - Historic destination with moderate pricing
- Madrid: $550 - Spanish capital with standard European pricing
- Barcelona: $580 - Popular Mediterranean destination
- Berlin: $525 - German capital with mid-range pricing

The use of `REPLACE INTO` instead of `INSERT INTO` is important because it handles both new entries and updates to existing prices without throwing errors. This makes the function robust and suitable for use in applications where prices might need to be updated regularly.

The lowercase conversion ensures that searches will work consistently regardless of how users type city names (e.g., "london", "LONDON", or "London" will all work the same way).

In [9]:
# Method to get price for a city
def get_city_price(city_name: str) -> float | None:
    """ Get the roundtrip ticket price to travel to the city """
    conn = sqlite3.connect("tickets.db")
    c = conn.cursor()
    c.execute("SELECT round_trip_price FROM cities WHERE city_name = ?", (city_name.lower(),))
    result = c.fetchone()
    conn.close()
    return result[0] if result else None

## Price Retrieval Function
Creates a function that queries the database to fetch roundtrip ticket prices for specified cities with proper error handling.
The function implements case-insensitive city name matching by converting input to lowercase, ensuring consistent lookups regardless of user input formatting.
Return value handling includes a None check to gracefully handle requests for cities not in the database, preventing runtime errors in agent interactions.
This function serves as a tool that AutoGen agents can use to access real pricing data, demonstrating the integration of AI agents with external data sources.

```mermaid
graph TD
    A[City Name Input] --> B[Convert to Lowercase]
    B --> C[Database Connection]
    C --> D[Execute SELECT Query]
    D --> E{Result Found?}
    E -->|Yes| F[Return Price]
    E -->|No| G[Return None]
    F --> H[Close Connection]
    G --> H
```

In [10]:
get_city_price("Rome")

499.0

## Function Testing
Tests the price retrieval function by fetching the roundtrip price for Rome, validating both function implementation and database connectivity.
This verification step ensures the function correctly queries the database and returns the expected price value (499.0 for Rome).
Testing individual components before integration is a crucial development practice that helps identify issues early in the development process.
The successful test confirms that the tool is ready for integration with AutoGen agents, providing confidence in the data layer functionality.

In [11]:
from autogen_agentchat.agents import AssistantAgent

smart_agent = AssistantAgent(
    name="smart_airline_agent",
    model_client=model_client,
    system_message="You are a helpful assistant for an airline. You give short, humorous answers, including the price of a roundtrip ticket.",
    model_client_stream=True,
    tools=[get_city_price],
    reflect_on_tool_use=True
)

## Tool-Enhanced Agent
Creates an advanced assistant agent with tool capabilities to query prices and reflection features for improved response accuracy.
The tools parameter integrates the `get_city_price` function, enabling the agent to access real pricing data during conversations and provide accurate information.
`reflect_on_tool_use=True` activates the agent's ability to analyze and validate its tool usage, leading to more reliable and contextually appropriate responses.
This demonstrates AutoGen's powerful tool integration capabilities, showing how agents can seamlessly combine language understanding with external data access and function execution.

```mermaid
graph TD
    A[User Query] --> B[Smart Agent]
    B --> C{Need Price Data?}
    C -->|Yes| D[Call get_city_price Tool]
    C -->|No| E[Generate Response]
    D --> F[Database Query]
    F --> G[Price Retrieved]
    G --> H[Reflection on Tool Use]
    H --> I[Enhanced Response with Price]
    E --> J[Regular Response]
    I --> K[Final Answer]
    J --> K
```

In [12]:
response = await smart_agent.on_messages([message], cancellation_token=CancellationToken())
for inner_message in response.inner_messages:
    print(inner_message.content)
response.chat_message.content

[FunctionCall(id='call_OpQPhbbvSddcMoOenY5orE5K', arguments='{"city_name":"London"}', name='get_city_price')]
[FunctionExecutionResult(content='299.0', name='get_city_price', call_id='call_OpQPhbbvSddcMoOenY5orE5K', is_error=False)]


'A trip to London? Brilliant choice! A roundtrip ticket will set you back about $299. Just remember, the only "fish and chips" policy we abide by is consuming them, not taking them as carry-ons! ✈️🍟'

## Tool-Enabled Response
Demonstrates the agent using the price retrieval tool to provide accurate pricing information in its response, showcasing the complete tool integration workflow.
The inner_messages output reveals the agent's internal process: first making a function call to get_city_price("London"), then receiving the execution result (299.0).
This transparency in agent reasoning helps developers understand how tools are being used and debug any issues in the integration process.
The final response combines the retrieved pricing data with the agent's humorous personality, showing how tool-enhanced agents maintain their character while providing factual information.

```mermaid
graph LR
    A[User: "I'd like to go to London"] --> B[Agent Processing]
    B --> C[Function Call: get_city_price("London")]
    C --> D[Database Returns: 299.0]
    D --> E[Function Result Processing]
    E --> F[Response Generation with Price]
    F --> G["Response: $299 + Humor"]
```